// <auto-generated />
using System;
using CRUD_Demo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CRUD_Demo.Migrations
{
    [DbContext(typeof(ProductsContext))]
    [Migration("20240229033000_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("CRUD_Demo.Models.Product", b =>
                {
                    b.Property<string>("Barcode")
                        .HasColumnType("VARCHAR");

                    b.Property<string>("Brand")
                        .HasColumnType("VARCHAR");

                    b.Property<string>("Name")
                        .HasColumnType("VARCHAR");

                    b.Property<double?>("PruchasePrice")
                        .HasColumnType("DOUBLE");

                    b.Property<double?>("SellingPrice")
                        .HasColumnType("DOUBLE");

                    b.HasKey("Barcode");

                    b.ToTable("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
